### PR TITLE
calculate sway from angular velocity

### PR DESCRIPTION
**Pull request by wbw383**
Hi,

Thanks for providing GT7Proxy!

I was experiencing some erratic behavior in sway...

After some research and testing I found that I could calculate the sway force based on the telemetry.angularvelocity_y
I don't know if it is 100% correct, but it feels good to me.

Feel free to take what you like and share this code.

-William Williams

### CODE REVIEW

**Comment by drowhunter** [comment]
could you explain what erratic behavior you experienced ?  I'm wondering if its the same thing I noticed.

**Comment by wbw383** [comment]
> could you explain what erratic behavior you experienced ? I'm wondering if its the same thing I noticed.

The sway values would start in the correct direction, but the suddenly shift to the opposite direction.
It seems unpredictable.  Initially, I thought perhaps just the sign was wrong, but correcting the sign alone did not fix the problem; the values were just not correct.

**Comment by vthinsel** [comment]
Hello,This is what can happen when going from -180 to 180…. Simtools has an option for this mitigation. I’ll double check and make comparisons with your approach which makes sense anyway. You noticed it on a specific track ?Cheers    ---- On ven., 16 févr. 2024 20:06:00 +0100  ***@***.***> wrote ----  
 
could you explain what erratic behavior you experienced ? I'm wondering if its the same thing I noticed. 
 
The sway values would start in the correct direction, but the suddenly shift to the opposite direction. 
It seems unpredictable.  Initially, I thought perhaps just the sign was wrong, but correcting the sign alone did not fix the problem; the values were just not correct.

**Comment by wbw383** [comment]
> Hello,This is what can happen when going from -180 to 180…. Simtools has an option for this mitigation. I’ll double check and make comparisons with your approach which makes sense anyway. You noticed it on a specific track ?

I tried the SimTools "Anti-rollover" toggle to mitigate this, and although it may have behaved differently, the values were still erratic and it did not feel good.

For testing, I use a Mazda MX5 on Tsukuba... but this sway issue can be experienced on any turn on any track.

**Comment by drowhunter** [comment]
I'm using Yaw 2 with Sim Racing Studio's GT7 profile , and I'm convinced they are not calculating the roll properly.  Check this video I made. [youtube video](https://www.youtube.com/watch?v=2llnF4OBE8w&t=27s),  and tell me if this is what you noticed. (You need to only focus on the Back view)

Notice at [27 seconds](https://www.youtube.com/watch?v=2llnF4OBE8w&t=27s) I'm on a straight and swerving left and right and the roll is in the opposite direction as expected.  But then (here's the problem) at [37 seconds](https://www.youtube.com/watch?v=2llnF4OBE8w&t=37s) I'm turning a left corner and its tilted in the same direction (it should be opposite)

If this script solves this issue,  what I am going to do on my fork of your script, is add SRS as an additional output and feed your correct values directly the rig, similar to what this guy did [grandturismo-srs-proxy](https://github.com/gt7coder/grandturismo-srs-proxy)](https://github.com/gt7coder/grandturismo-srs-proxy/blob/main/gt_packet_definition.py)

at least I'm pretty sure it will work.

**Comment by vthinsel** [comment]
For me, calculating a force based on weight and angles is not correct. Sway is a force, which can be calculated based on lateral speed and only lateral speed. No matter if your weight is 10Kg or 1000Kg, the force is the same. We have the local velocity vector based on quaternion so it is pretty easy to compute the local forces vector. You seem to calculate a mix of traction loss with a mass pultiplier.
I have made a new short video focusing on roll/pitch/yaw/heave/sway/surge/traction loss (by the way, roll/pitch/yaw were inverted before the release I made today) : https://youtu.be/y-9C2CPViKQ
As you can see, sway behaves pretty accurately, you can notice it when pulling the hand brake : the driver is "pushed" on left or right side. You can notice it also when "climbing" the road going from flat to 20° roll angle.
Simtools filtering can be usefull, especially on heave to make it less "jumpy", depending also on you min/max settings.

**Comment by wbw383** [comment]
I see in the video... on the left turn and turning left, the sway moves to
the right, but then also to the left.
Would you agree that the sway force felt while turning around a constant
curve should be constant?
If you drive in tight circles in a car, you would feel the sway force the
entire time.
On my SimRig, I would feel the sway push to the right (correctly) but then
immediately shift left while I am still turning.

I didn't know how to calculate sway based on the math you had, so I just
had to figure out the physics/math for myself.
I'm sure your method can work as well, but it doesn't feel right at the
moment...

(The inversions you had were reversed via SimTools)

**Pull request closed without merging**
